;;;; color-schemes.css hold each background, color, color...

;;;; For cover-image->color-scheme:
;;;; 1) find appropriate colors from image
;;;; 2) calculate readability and improve when possible

(2019 (7 "Blood, Sweat, and Pixels" "Jason Schreier" "blood-sweat-and-pixels" 500)
      (6 "Tribe" "Sebastian Junger" "tribe" 520)
      (5 "Brain on Fire" "Susannah Cahalan" "brain-on-fire" 520)
      (4 "Infinite" "Jeremy Robinson" "infinite" 550)
      (3 "The Satyricon" "Petronius" "the-satyricon" 550)
      (2 "No Surrender: My Thirty-Year War" "Hiroo Onoda" "no-surrender" 540)
      (1 "One Flew Over the Cuckoo's Nest" "Ken Kesey" "one-flew-over" 570))

(2018 (27 "Ham on Rye: A Novel" "Charles Bukowski" "ham-on-rye" 510)
      (26 "Shogun" "James Clavell" "shogun" 510)
      (25 "Hard Boiled Wonderland and the End of the World" "Haruki Murakami" "hard-boiled" 540)
      (24 "Computer Networks and Internets" "Douglas E. Comer" "computer-networks" 540)
      (23 "Fahrenheit 451" "Ray Bradbury" "fahrenheit-451" 530)
      (22 "So Good They Can't Ignore You" "Cal Newport" "so-good" 530)
      (21 "The Moon Is a Harsh Mistress" "Robert A. Heinlein" "moon-mistress" 530)
      (20 "The Color of Law: A Forgotten History" "Richard Rothstein" "color-of-law" 530)
      (19 "Practical Common Lisp" "Peter Seibel" "pcl" 510)
      (18 "Theft by Finding: Diaries" "David Sedaris" "theft-by-finding" 530)
      (17 "Starman Jones" "Robert A. Heinlein" "starman-jones" 550)
      (16 "Red Notice" "Bill Browder" "red-notice" 520)
      (15 "The Lathe of Heaven" "Ursula Le Guin" "lathe-of-heaven" 540)
      (14 "The Case Against Education" "Bryan Caplan" "case-against-education" 550)
      (13 "Flowers for Algernon" "Daniel Keyes" "flowers-for-algernon" 550)
      (12 "Operating System Design: The XINU Approach" "Douglas E. Comer" "os-xinu" 570)
      (11 "Blood Meridian" "Cormac McCarthy" "blood-meridian" 590)
      (10 "All Systems Red" "Martha Wells" "all-systems-red" 590)
      (9 "Interview with the Vampire" "Anne Rice" "interview-vampire" 570)
      (8 "A Gentle Intro to Symbolic Computation" "David S. Touretzky" "gentle" 550)
      (7 "Evicted: Poverty and Profit in the American City" "Matthew Desmond" "evicted" 540)
      (6 "Pimp: The Story of My Life" "Iceberg Slim" "pimp" 540)
      (5 "Till We Have Faces: A Myth Retold" "C. S. Lewis" "have-faces" 550)
      (4 "Up From Slavery" "Booker T. Washington" "up-from-slavery" 540)
      (3 "The Three Body Problem" "Cixin Liu" "three-body-problem" 540)
      (2 "Lolita" "Vladimir Nabokov" "lolita" 570)
      (1 "God" "Reza Aslan" "god" 590))

(2017 (32 "Ready Player One" "Ernest Cline" "ready-player-one" 540)
      (31 "The Call of the Wild" "Jack London" "call-of-the-wild" 540)
      (30 "Never Let Me Go" "Kazuo Ishiguro" "never-let-me-go" 540)
      (29 "Attempting Normal" "Marc Maron" "attempting-normal" 540)
      (28 "Essential of Computer Architecture" "Douglas E. Comer"
          "essentials-computer-architecture" 550)
      (27 "Junkie" "William S. Burroughs" "junkie" 540)
      (26 "The Sixth Extinction: An Unnatural History" "Elizabeth Kolbert" "sixth-extinction" 540)
      (25 "The Art of Invisibility" "Kevin Mitnick" "art-invisibility" 550)
      (24 "It" "Stephen King" "it" 550)
      (23 "The Persistence of Vision" "John Varley" "persistence-of-vision" 550)
      (22 "The Remains of the Day" "Kazuo Ishiguro" "remains-of-the-day" 570)
      (21 "The Righteous Mind" "Jonathan Haidt" "righteous-mind" 590)
      (20 "Norwegian Wood" "Haruki Murakami" "norwegian-wood" 590)
      (19 "The Brothers Karamazov" "Fyodor Dostoyevsky" "brothers-karamazov" 570)
      (18 "American Gods" "Neil Gaiman" "american-gods" 590)
      (17 "Homo Deus" "Yuval Noah Harari" "homo-deus" 540)
      (16 "Norse Mythology" "Neil Gaiman" "norse-mythology" 540)
      (15 "Neuromancer" "William Gibson" "neuromancer" 540)
      (14 "Why We Hate the Oil Companies" "John Hofmeister" "hate-the-oil" 540)
      (13 "Discrete Mathematics and Its Applications" "Kenneth H. Rosen" "discrete-math" 550)
      (12 "The Soul of a New Machine" "Tracy Kidder" "soul-of-a-new-machine" 550)
      (11 "The Great Unknown" "Marcus du Sautoy" "great-unknown" 550)
      (10 "1984" "George Orwell" "1984" 570)
      (9 "When You Are Engulfed in Flames" "David Sedaris" "engulfed-in-flames" 590)
      (8 "A Knight of the Seven Kingdoms" "George R. R. Martin" "seven-kingdoms" 590) 
      (7 "C Programming Language" "Brian W. Kernighan, Dennis M. Ritchie" "c-lang" 570)
      (6 "Soul of An Octopus" "Sy Montgomery" "soul-of-an-octopus" 540)
      (5 "A Farewell to Arms" "Ernest Hemingway" "farewell-to-arms" 550)
      (4 "Consider the Lobster and Other Essays" "David Foster Wallace" "consider-lobster" 550)
      (3 "Born a Crime" "Trevor Noah" "born-a-crime" 550)
      (2 "Hillbilly Elegy" "J. D. Vance" "hillbilly-elegy" 570)
      (1 "Sundown Towns" "James Loewen" "sundown-towns" 590))

(2016 (24 "The Alchemist" "Paulo Coelho" "the-alchemist" 570)
      (23 "Infinite Jest" "David Foster Wallace" "infinite-jest" 550)
      (22 "A Supposedly Fun Thing I'll Never Do Again" "David Foster Wallace" "sup-fun-thing" 570)
      (21 "Bury My Heart at Wounded Knee" "Dee Brown" "bury-my-heart" 590)
      (20 "Code: The Hidden Language" "Charles Petzold" "code-hidden-lang" 590)
      (19 "Postcapitalism" "Paul Mason" "postcapitalism" 550)
      (18 "A Short History of Nearly Everything" "Bill Bryson" "short-history-everything" 590)
      (17 "Ego is the Enemy" "Ryan Holiday" "ego-enemy" 540)
      (16 "Meditations" "Marcus Aurelius" "meditations" 540)
      (15 "Murder in the Bayou" "Ethan Brown" "murder-bayou" 550)
      (14 "Crime and Punishment" "Fyodor Dostoyevsky" "crime-and-punishment" 550)
      (13 "Cat's Cradle" "Kurt Vonnegut" "cats-cradle" 550)
      (12 "Under the Banner of Heaven" "John Krakauer" "banner-of-heaven" 570)
      (11 "The Girl on the Train" "Paula Hawkins" "girl-on-the-train" 590)
      (10 "You Can't Win" "Jack Black" "you-cant-win" 590)
      (9 "But How Do It Know?" "John C. Scott" "but-how-know" 570)
      (8 "Sapiens" "Yuval Noah Harari" "sapiens" 590)
      (7 "Season of the Witch" "David Talbot" "season-of-the-witch" 540)
      (6 "Slaughterhouse-Five" "Kurt Vonnegut" "slaughterhouse-five" 540)
      (5 "Creativity, Inc." "Ed Catmull, Amy Wallace" "creativity-inc" 550)
      (4 "The Count of Monte Cristo" "Alexandre Dumas" "monte-cristo" 550)
      (3 "A Confederacy of Dunces" "John Kennedy Toole" "confederacy-of-dunces" 550)
      (2 "Atlas Shrugged" "Ayn Rand" "atlas-shrugged" 570)
      (1 "Elon Musk" "Ashlee Vance" "elon-musk" 590))



